# Generated by Django 3.0.4 on 2020-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.CharField(choices=[('verified', '승인됨'), ('unverified', '승인대기')], default='unverified', max_length=10),
        ),
    ]
