# Generated by Django 3.0.4 on 2020-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_s', '0002_user_verify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['start_time'], 'verbose_name': '예약', 'verbose_name_plural': '예약 목록'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.TextField(default='0', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='s_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
